/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelOffice;

import Business.TravelOffice.Customer.Customer;
import Business.TravelOffice.Customer.CustomerDirectory;
import Business.TravelOffice.TravelOffice;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gaomc
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerJPanel
     */
    
//    private List<Customer> customerList;
    private CustomerDirectory customerDirectory;
    private JPanel cardSequenceJPanel;
    private TravelOffice travelOffice;
    
    
    public ManageCustomerJPanel(JPanel cardSequenceJPanel, TravelOffice travelOffice) {
        initComponents();
        this.travelOffice = travelOffice;
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.customerDirectory = travelOffice.getCustomerDirectory();
        System.out.println("1");
        System.out.println(customerDirectory.getCustomerList());
        populate(customerDirectory.getCustomerList());
    }
    
    public void populate(List<Customer> customerList){
        DefaultTableModel dtm = (DefaultTableModel)customerJTable.getModel();
        dtm.setRowCount(0);
        
        customerList.forEach((Customer customer) -> {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = customer;
            row[1] = customer.getId();
            row[2] = customer.getIdentityType() + customer.getIdentityID();
            row[3] = customer.getOfficeInfo();
            row[4] = customer.getTicket();
            
            dtm.addRow(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerManageJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerJTable = new javax.swing.JTable();
        viewCustomerBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        createCustomer = new javax.swing.JButton();

        customerManageJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(customerManageJTable);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer", "Member ID", "Identity Info", "Office Info", "Ticket Info"
            }
        ));
        jScrollPane2.setViewportView(customerJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 390, 220));

        viewCustomerBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewCustomerBtn.setText("View Customer");
        viewCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerBtnActionPerformed(evt);
            }
        });
        add(viewCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 330, 150, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Customer List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 150, -1));

        createCustomer.setBackground(new java.awt.Color(255, 255, 255));
        createCustomer.setText("Create Customer");
        createCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCustomerActionPerformed(evt);
            }
        });
        add(createCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        
        Component[] comps = cardSequenceJPanel.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageCustomerJPanel){
            ManageCustomerJPanel manageP = (ManageCustomerJPanel) comp;
            manageP.populate(customerDirectory.getCustomerList());
            }
        }
        layout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void viewCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = customerJTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }else{
            Customer customer = (Customer) customerJTable.getValueAt(selectedRow, 0);
            ViewCustomerJPanel panel = new ViewCustomerJPanel(cardSequenceJPanel, customer, customerDirectory);
            cardSequenceJPanel.add(panel);
            CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
            layout.next(cardSequenceJPanel); 
        }
    }//GEN-LAST:event_viewCustomerBtnActionPerformed

    private void createCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomerActionPerformed
        // TODO add your handling code here:
        Customer customer = new Customer(travelOffice);
        CreateCustomerJPanel panel = new CreateCustomerJPanel(cardSequenceJPanel, customer, customerDirectory);
        cardSequenceJPanel.add(panel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel); 
    }//GEN-LAST:event_createCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createCustomer;
    private javax.swing.JTable customerJTable;
    private javax.swing.JTable customerManageJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton viewCustomerBtn;
    // End of variables declaration//GEN-END:variables
}
