/*
 * HappyLamb - TravelAgencySystem
 * Each line should be prefixed with  * 
 */
package UserInterface.TravelOffice;

import Business.Airliner.Flight.Flight;
import Business.TravelOffice.Customer.Customer;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author gaomc
 */
public class SelectSeatJPanel extends javax.swing.JPanel {

    private Flight flight;
    private Customer customer;
    
    SelectSeatJPanel(Flight flight, Customer customer) {
        initComponents();
        this.flight = flight;
        this.customer = customer;
        SeatNumberComBox.setModel(new DefaultComboBoxModel(this.flight.getAvaliableSeat().toArray()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SeatNumberComBox = new javax.swing.JComboBox<>();
        bookTicketBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Choose a seat");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, 20));

        jLabel2.setText("Avaliable Seat:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 20));

        SeatNumberComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SeatNumberComBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNumberComBoxActionPerformed(evt);
            }
        });
        add(SeatNumberComBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 30));

        bookTicketBtn.setText("Confirm Booking Ticket");
        bookTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketBtnActionPerformed(evt);
            }
        });
        add(bookTicketBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        backBtn.setText("Back <<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bookTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketBtnActionPerformed
        // TODO add your handling code here:
        
        String selectedSeat = SeatNumberComBox.getSelectedItem().toString();
        this.flight.SeatAssignment(customer, selectedSeat);
       
        
    }//GEN-LAST:event_bookTicketBtnActionPerformed

    private void SeatNumberComBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNumberComBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNumberComBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SeatNumberComBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bookTicketBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
