/*
 * HappyLamb - TravelAgencySystem
 * Each line should be prefixed with  * 
 */
package UserInterface.TravelOffice;

import Business.TravelOffice.Customer.Customer;
import Business.TravelOffice.Customer.CustomerDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author gaomc
 */
public class ViewCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomer
     */
    private JPanel cardSequenceJPanel;
    private Customer customer;
    private List<Customer> customerList;
    

    public ViewCustomerJPanel(JPanel cardSequenceJPanel, Customer customer, CustomerDirectory customreDirectory) {
        initComponents();
        identityTypeComBox.setModel(new DefaultComboBoxModel(new String[]{"Passport","DriverLicense","Others"}));      

        
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.customer = customer;
        this.customerList = customreDirectory.getCustomerList();
        
        nameTextField.setText(customer.getName());
        membershipIDTextField.setText(customer.getId());
        identityTypeComBox.setSelectedItem(customer.getIdentityType());
        identityIDTextField.setText(customer.getIdentityID());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        membershipIDTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        identityIDTextField = new javax.swing.JTextField();
        updateCustomerBtn = new javax.swing.JButton();
        saveCustomerBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ticketInfoTextField = new javax.swing.JTextField();
        identityTypeComBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 30));

        nameTextField.setEnabled(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, -1));

        jLabel3.setText("Membership ID: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 30));

        membershipIDTextField.setEnabled(false);
        membershipIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membershipIDTextFieldActionPerformed(evt);
            }
        });
        add(membershipIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 150, -1));

        jLabel4.setText("Identity Info: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 30));

        identityIDTextField.setEnabled(false);
        identityIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identityIDTextFieldActionPerformed(evt);
            }
        });
        add(identityIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 150, -1));

        updateCustomerBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateCustomerBtn.setText("Update");
        updateCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerBtnActionPerformed(evt);
            }
        });
        add(updateCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, -1));

        saveCustomerBtn.setBackground(new java.awt.Color(255, 255, 255));
        saveCustomerBtn.setText("Save");
        saveCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerBtnActionPerformed(evt);
            }
        });
        add(saveCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 100, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Customer Info");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 100, -1));

        jLabel5.setText("Ticket Info:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 30));

        ticketInfoTextField.setEnabled(false);
        ticketInfoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketInfoTextFieldActionPerformed(evt);
            }
        });
        add(ticketInfoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 150, -1));

        identityTypeComBox.setBackground(new java.awt.Color(255, 255, 255));
        identityTypeComBox.setEditable(true);
        identityTypeComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        identityTypeComBox.setEnabled(false);
        add(identityTypeComBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void membershipIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membershipIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membershipIDTextFieldActionPerformed

    private void identityIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identityIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identityIDTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        
        Component[] comps = cardSequenceJPanel.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageCustomerJPanel){
            ManageCustomerJPanel manageP = (ManageCustomerJPanel) comp;
            manageP.populate(customerList);
            }
        }
        layout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerBtnActionPerformed
        // TODO add your handling code here:
        nameTextField.setEnabled(true);
        identityIDTextField.setEnabled(true);
        identityTypeComBox.setEnabled(true);
        membershipIDTextField.setEnabled(true);       
    }//GEN-LAST:event_updateCustomerBtnActionPerformed

    private void saveCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerBtnActionPerformed
        // TODO add your handling code here:
        nameTextField.setEnabled(false);
        identityIDTextField.setEnabled(false);
        identityTypeComBox.setEnabled(false);
        membershipIDTextField.setEnabled(false);
        
        customer.setName(nameTextField.getText());
        customer.setIdentityType(identityTypeComBox.getSelectedItem().toString());
        customer.setIdentityID(identityIDTextField.getText());      
    }//GEN-LAST:event_saveCustomerBtnActionPerformed

    private void ticketInfoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketInfoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketInfoTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField identityIDTextField;
    private javax.swing.JComboBox<String> identityTypeComBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField membershipIDTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton saveCustomerBtn;
    private javax.swing.JTextField ticketInfoTextField;
    private javax.swing.JButton updateCustomerBtn;
    // End of variables declaration//GEN-END:variables
}
