/*
 * HappyLamb - TravelAgencySystem
 * Each line should be prefixed with  * 
 */
package UserInterface.TravelAgency;

import Business.Airliner.Fleet.Airplane;
import Business.Ticket.Ticket;
import Business.TravelAgency.TravelAgency;
import Business.TravelOffice.Customer.Customer;
import Business.TravelOffice.TravelOffice;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sallywang
 */
public class ViewTravelOfficeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewTravelOfficeJPanel
     */
    private TravelOffice travelOffice;
    private JPanel cardSequenceJPanel;
    public ViewTravelOfficeJPanel(TravelOffice travelOffice, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelOffice = travelOffice;
        this.cardSequenceJPanel = cardSequenceJPanel;
        init();
    }

    private void init(){
        this.indexjTextField.setText(this.travelOffice.getId()+"");
        this.namejTextField.setText(this.travelOffice.getName());
        
        populateCustomerTable();
        populateTicketTable();
    }
    
    private void populateCustomerTable(){
        DefaultTableModel dfm = (DefaultTableModel)customerjTable.getModel();
        dfm.setRowCount(0);
        travelOffice.getCustomerDirectory().getCustomerList().forEach((Customer customer)->{
            Object[] row = new Object[dfm.getColumnCount()];
            row[0] = customer;
            row[1] = customer.getId();
            row[2] = customer.getIdentityType();
            row[3] = customer.getIdentityID();
            
            dfm.addRow(row);
        });
    }
    
    private void populateTicketTable(){
        DefaultTableModel dfm = (DefaultTableModel)ticketsjTable.getModel();
        dfm.setRowCount(0);
        travelOffice.getTicketDirectory().getTicketList().forEach((Ticket ticket)->{
            System.out.println("Tickets:::::::");
            Object[] row = new Object[dfm.getColumnCount()];
            row[0] = ticket;
            row[1] = ticket.getCustomerInfo();
            row[2] = ticket.getFlightNumber();
            row[3] = ticket.getAirplaneInfo();
            row[4] = ticket.getSeatInfo();
            row[5] = ticket.isPending();
            
            dfm.addRow(row);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerjTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticketsjTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        modifyjButton = new javax.swing.JButton();
        namejTextField = new javax.swing.JTextField();
        indexjTextField = new javax.swing.JTextField();
        savejButton = new javax.swing.JButton();
        confirmTicketjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("index：");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 58, -1, -1));

        jLabel2.setText("name：");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 93, -1, -1));

        customerjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "name", "id", "identity type", "identity number"
            }
        ));
        jScrollPane1.setViewportView(customerjTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 149, 581, 134));

        jLabel3.setText("tickets:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 289, -1, -1));

        jLabel4.setText("customers:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 127, -1, -1));

        ticketsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ticket number", "customer", "filght number", "airplane", "seat number", "pending"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ticketsjTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 311, 581, 134));

        backjButton.setText("<< back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 21, -1, -1));

        modifyjButton.setText("modify");
        modifyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(modifyjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 28, -1, -1));

        namejTextField.setEditable(false);
        jPanel1.add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 88, 80, -1));

        indexjTextField.setEditable(false);
        indexjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexjTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(indexjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 53, 80, -1));

        savejButton.setText("save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });
        jPanel1.add(savejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 28, -1, -1));

        confirmTicketjButton.setText("confirm ticket");
        confirmTicketjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmTicketjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmTicketjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 457, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)cardSequenceJPanel.getLayout();
        cardSequenceJPanel.remove(this);
        layout.previous(cardSequenceJPanel);

        Component[] comps = cardSequenceJPanel.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageTravelOfficeJPanel){
                ManageTravelOfficeJPanel manage = (ManageTravelOfficeJPanel)comp;
                manage.populate();
            }
        }

    }//GEN-LAST:event_backjButtonActionPerformed

    private void modifyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyjButtonActionPerformed
        // TODO add your handling code here:
        this.modifyjButton.setEnabled(false);
        this.namejTextField.setEditable(true);
        this.savejButton.setEnabled(true);
    }//GEN-LAST:event_modifyjButtonActionPerformed

    private void indexjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexjTextFieldActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
        String name = namejTextField.getText();
        if(name.equals(null)||name.startsWith(" ")){
            JOptionPane.showMessageDialog(null, "Please do not input name start with space");
            this.modifyjButton.setEnabled(true);
            this.namejTextField.setEditable(false);
            this.savejButton.setEnabled(false);
            this.namejTextField.setText(travelOffice.getName());
        }else if(name.equals(travelOffice.getName())){
            JOptionPane.showMessageDialog(null, "It is the same as before, nothing modified");
            this.modifyjButton.setEnabled(true);
            this.namejTextField.setEditable(false);
            this.savejButton.setEnabled(false);
            this.namejTextField.setText(travelOffice.getName());
        }else{
            JOptionPane.showMessageDialog(null, "Modified Successfully");
            travelOffice.setName(name);
            this.modifyjButton.setEnabled(true);
            this.namejTextField.setEditable(false);
            this.savejButton.setEnabled(false);
            this.namejTextField.setText(travelOffice.getName());
        }
    }//GEN-LAST:event_savejButtonActionPerformed

    private void confirmTicketjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmTicketjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.ticketsjTable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            Ticket ticket = (Ticket)this.ticketsjTable.getValueAt(selectedRow, 0);
            JOptionPane.showMessageDialog(null, "Success generated a ticket, ticket into:\n"
                    + "ticket number:" + ticket.getTicketNumber() +"\n"
                    + "customer information" + ticket.getCustomerInfo() +"\n"
                    + "flight number" + ticket.getFlightInfo() + "\n"
                    + "seat information" + ticket.getSeatInfo() + "\n"
                    + "\n"
                    + "Order generated and send to the Airliner" + ticket.getAirlinerName()
            );
            ticket.setPending(false);
            populateTicketTable();
            
            ticket.getAirliner().addOrderedTicket(ticket);
            
        }
        
    }//GEN-LAST:event_confirmTicketjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JButton confirmTicketjButton;
    private javax.swing.JTable customerjTable;
    private javax.swing.JTextField indexjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifyjButton;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JButton savejButton;
    private javax.swing.JTable ticketsjTable;
    // End of variables declaration//GEN-END:variables
}
