/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.Airliner.Airliner;
import Business.Airliner.Fleet.Airplane;
import Business.Airliner.Flight.Flight;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gaomc
 */
public class ViewAirLinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirLinerJPanel
     */
    private Airliner airliner;
    private JPanel cardSequenceJPanel;
    
    public ViewAirLinerJPanel(Airliner airliner, JPanel cardSequenceJPanel) {
        initComponents();
        this.airliner = airliner;
        this.cardSequenceJPanel = cardSequenceJPanel;
        
        init();
                
    }
    
    private void init(){
        this.indexjTextField.setEditable(false);
        this.namejTextField.setEditable(false);
        this.modifyjButton.setEnabled(true);
        this.savejButton.setEnabled(false);
        this.indexjTextField.setText(airliner.getId());
        this.namejTextField.setText(airliner.getName());
        populateAirPlaneTable();
        populateFlightTable();
        
        
    }
    
    private void populateAirPlaneTable(){
        DefaultTableModel dfm = (DefaultTableModel)airplanejTable.getModel();
        dfm.setRowCount(0);
        airliner.getAirplaneDirectory().getAirplaneList().forEach((Airplane airplane)->{
            Object[] row = new Object[dfm.getColumnCount()];
            row[0] = airplane.getName();
            row[1] = airplane.getSeatNumber();
            row[2] = airplane.getSerialNum();
            
            dfm.addRow(row);
        });
        
    }
    
    private void populateFlightTable(){
        DefaultTableModel dfm = (DefaultTableModel)flightsjTable2.getModel();
        dfm.setRowCount(0);
        airliner.getFlightSchedual().getFlghtList().forEach((Flight flight)->{
            Object[] row = new Object[dfm.getColumnCount()];
            row[0] = flight.getFlightNo();
            row[1] = flight.getDeparture();
            row[2] = flight.getDestination();
            row[3] = flight.getDate();
            row[4] = flight.getStartTime().format(DateTimeFormatter.ISO_TIME);
            row[5] = flight.getArriveTime().format(DateTimeFormatter.ISO_TIME);
            row[6] = flight.getPrice() + "";
            
            dfm.addRow(row);
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplanejTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        flightsjTable2 = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        modifyjButton = new javax.swing.JButton();
        namejTextField = new javax.swing.JTextField();
        indexjTextField = new javax.swing.JTextField();
        savejButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("index：");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 58, -1, -1));

        jLabel2.setText("name：");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 93, -1, -1));

        airplanejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "model number", "seat number", "serial number"
            }
        ));
        jScrollPane1.setViewportView(airplanejTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 149, 581, 134));

        jLabel3.setText("flights:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 289, -1, -1));

        jLabel4.setText("airplanes:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 127, -1, -1));

        flightsjTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "flight number", "departure", "destination", "date", "start time", "arrive time", "price"
            }
        ));
        jScrollPane2.setViewportView(flightsjTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 311, 581, 134));

        backjButton.setText("<< back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 21, -1, -1));

        modifyjButton.setText("modify");
        modifyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyjButtonActionPerformed(evt);
            }
        });
        add(modifyjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 28, -1, -1));

        namejTextField.setEditable(false);
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 88, 80, -1));

        indexjTextField.setEditable(false);
        indexjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexjTextFieldActionPerformed(evt);
            }
        });
        add(indexjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 53, 80, -1));

        savejButton.setText("save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });
        add(savejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 28, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)cardSequenceJPanel.getLayout();
        cardSequenceJPanel.remove(this);
        layout.previous(cardSequenceJPanel);
        
        Component[] comps = cardSequenceJPanel.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageAirlinerJPanel){
                ManageAirlinerJPanel manage = (ManageAirlinerJPanel)comp;
                manage.populate();
            }
        }
        
    }//GEN-LAST:event_backjButtonActionPerformed

    private void modifyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyjButtonActionPerformed
        // TODO add your handling code here:
        this.modifyjButton.setEnabled(false);
        this.namejTextField.setEditable(true);
        this.savejButton.setEnabled(true);   
    }//GEN-LAST:event_modifyjButtonActionPerformed

    private void indexjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexjTextFieldActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
        String name = namejTextField.getText();
        if(name.equals(null)||name.startsWith(" ")){
            JOptionPane.showMessageDialog(null, "Please do not input name start with space");
            this.modifyjButton.setEnabled(true);
            this.namejTextField.setEditable(false);
            this.savejButton.setEnabled(false);
            this.namejTextField.setText(airliner.getName());
        }else if(name.equals(airliner.getName())){
            JOptionPane.showMessageDialog(null, "It is the same as before, nothing modified");  
            this.modifyjButton.setEnabled(true);
            this.namejTextField.setEditable(false);
            this.savejButton.setEnabled(false);
            this.namejTextField.setText(airliner.getName());
        }else{
            JOptionPane.showMessageDialog(null, "Modified Successfully");  
            airliner.setName(name);
            this.modifyjButton.setEnabled(true);
            this.namejTextField.setEditable(false);
            this.savejButton.setEnabled(false);
            this.namejTextField.setText(airliner.getName());
        }
    }//GEN-LAST:event_savejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airplanejTable;
    private javax.swing.JButton backjButton;
    private javax.swing.JTable flightsjTable2;
    private javax.swing.JTextField indexjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifyjButton;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JButton savejButton;
    // End of variables declaration//GEN-END:variables
}
