/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import Business.Airliner.Airliner;
import Business.Airliner.Flight.Flight;
import Business.Airliner.Flight.FlightSchedual;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gaomc
 */
public class ManageFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinerFlightScheduleJPanel
     */
    private FlightSchedual flightList;
    private Flight flight;
    private JPanel cardSequenceJPanel;
    private JPanel CreateNewJPanel;
    private Airliner airliner;
   
    public ManageFlightJPanel(JPanel cardSequenceJPanel, Airliner airliner) {
        initComponents();
        this.flightList = flightList;
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.airliner = airliner;
        this.flightList = airliner.getFlightSchedual();
        populateTable();
    }
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)viewTable.getModel();
        dtm.setRowCount(0);
        for(Flight flight: flightList.getFlghtList()){
            Object[] row = new Object[4];
            row[0]= flight;
            row[1]= flight.getRoute();
            row[2]= flight.getDate();
            row[3]= flight.getPrice();
            dtm.addRow(row);
        }
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        viewFlightBtn = new javax.swing.JButton();
        newFlightBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Flight  No.", "Route", "Date", "Price($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 135, 440, 160));

        jLabel1.setText("Manage Flights");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 95, -1, -1));

        viewFlightBtn.setText("View Flight >>");
        viewFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFlightBtnActionPerformed(evt);
            }
        });
        add(viewFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        newFlightBtn.setText("New Flight >>");
        newFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFlightBtnActionPerformed(evt);
            }
        });
        add(newFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        deleteBtn.setText("Delete Flight ");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 135, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = viewTable.getSelectedRow();
        
        if(selectedrow >= 0){           
            Flight flight = (Flight)viewTable.getValueAt(selectedrow, 0);
            flightList.deleteFlight(flight);
            JOptionPane.showMessageDialog(null, "delete sucessfully");
            populateTable();
        }else            
            JOptionPane.showMessageDialog(null, "Please select any row");
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFlightBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewTable.getSelectedRow();
        if (selectedRow>=0){
            flight= (Flight) viewTable.getValueAt(selectedRow, 0);
            FlightDetailJPanel ff = new FlightDetailJPanel(cardSequenceJPanel, flight,airliner);
            cardSequenceJPanel.add(ff);
            CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
            layout.next(cardSequenceJPanel);
        }else{
            JOptionPane.showMessageDialog(null,"Please select a row from table first!","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewFlightBtnActionPerformed

    private void newFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFlightBtnActionPerformed
        // TODO add your handling code here:
        CreateNewFlight ff = new CreateNewFlight(cardSequenceJPanel,flightList,airliner);
        cardSequenceJPanel.add(ff);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_newFlightBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newFlightBtn;
    private javax.swing.JButton viewFlightBtn;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
