/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.volunteer.medicineManage;

/**
 *
 * @author gaomc
 */
public class MedicineManageButtonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicineManageButtonJPanel
     */
    public MedicineManageButtonJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processMedicalRequestBtn = new javax.swing.JButton();
        contactPharmacyBtn = new javax.swing.JButton();
        checkStockBtn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processMedicalRequestBtn.setText("Process Medical Request");
        processMedicalRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processMedicalRequestBtnActionPerformed(evt);
            }
        });
        add(processMedicalRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        contactPharmacyBtn.setText("Contact Manufactuer");
        contactPharmacyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactPharmacyBtnActionPerformed(evt);
            }
        });
        add(contactPharmacyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        checkStockBtn2.setText("Check Stock");
        checkStockBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStockBtn2ActionPerformed(evt);
            }
        });
        add(checkStockBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 100, -1, -1));

        jLabel1.setText("// ask for sepecific medicine ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel2.setText("// update stock");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel3.setText("// approve / decline request");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processMedicalRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processMedicalRequestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processMedicalRequestBtnActionPerformed

    private void contactPharmacyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactPharmacyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactPharmacyBtnActionPerformed

    private void checkStockBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStockBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkStockBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkStockBtn2;
    private javax.swing.JButton contactPharmacyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton processMedicalRequestBtn;
    // End of variables declaration//GEN-END:variables
}
