/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.volunteer.finance;

/**
 *
 * @author gaomc
 */
public class FinanceButtonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinanceButtonJPanel
     */
    public FinanceButtonJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkGovFundingBtn = new javax.swing.JButton();
        checkBalanceBtn1 = new javax.swing.JButton();
        checkDonationBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkGovFundingBtn.setText("Check Government Funding");
        checkGovFundingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGovFundingBtnActionPerformed(evt);
            }
        });
        add(checkGovFundingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        checkBalanceBtn1.setText("Check Balance");
        add(checkBalanceBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        checkDonationBtn1.setText("Check Donation");
        checkDonationBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDonationBtn1ActionPerformed(evt);
            }
        });
        add(checkDonationBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel1.setText("// request new funding");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel2.setText("// check balance and history");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel3.setText("// check funding history");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void checkGovFundingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGovFundingBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkGovFundingBtnActionPerformed

    private void checkDonationBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDonationBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDonationBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkBalanceBtn1;
    private javax.swing.JButton checkDonationBtn1;
    private javax.swing.JButton checkGovFundingBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
