/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.patients;

/**
 *
 * @author gaomc
 */
public class PatientsButtonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientsButtonJPanel
     */
    public PatientsButtonJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findDoctorBtn2 = new javax.swing.JButton();
        viewQuestionHistoryBtn1 = new javax.swing.JButton();
        checkNotificationBtn = new javax.swing.JButton();
        donateBtn = new javax.swing.JButton();
        viewMedicalRecordBtn1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        findDoctorBtn2.setBackground(new java.awt.Color(255, 255, 255));
        findDoctorBtn2.setText("Find a Doctor");
        findDoctorBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findDoctorBtn2ActionPerformed(evt);
            }
        });
        add(findDoctorBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        viewQuestionHistoryBtn1.setBackground(new java.awt.Color(255, 255, 255));
        viewQuestionHistoryBtn1.setText("View Question History");
        viewQuestionHistoryBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewQuestionHistoryBtn1ActionPerformed(evt);
            }
        });
        add(viewQuestionHistoryBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        checkNotificationBtn.setBackground(new java.awt.Color(255, 255, 255));
        checkNotificationBtn.setText("Check Notification");
        checkNotificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNotificationBtnActionPerformed(evt);
            }
        });
        add(checkNotificationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        donateBtn.setBackground(new java.awt.Color(255, 255, 255));
        donateBtn.setText("Donate");
        donateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBtnActionPerformed(evt);
            }
        });
        add(donateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        viewMedicalRecordBtn1.setBackground(new java.awt.Color(255, 255, 255));
        viewMedicalRecordBtn1.setText("View Medical Record");
        viewMedicalRecordBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedicalRecordBtn1ActionPerformed(evt);
            }
        });
        add(viewMedicalRecordBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void findDoctorBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findDoctorBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findDoctorBtn2ActionPerformed

    private void viewQuestionHistoryBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewQuestionHistoryBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewQuestionHistoryBtn1ActionPerformed

    private void checkNotificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNotificationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkNotificationBtnActionPerformed

    private void donateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donateBtnActionPerformed

    private void viewMedicalRecordBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedicalRecordBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMedicalRecordBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkNotificationBtn;
    private javax.swing.JButton donateBtn;
    private javax.swing.JButton findDoctorBtn2;
    private javax.swing.JButton viewMedicalRecordBtn1;
    private javax.swing.JButton viewQuestionHistoryBtn1;
    // End of variables declaration//GEN-END:variables
}
