/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ButtonSide;

/**
 *
 * @author gaomc
 */
public class TravelAgencyBtnJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerBtn
     */
    public TravelAgencyBtnJPanel() {
        //jhghj
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageAirlinerBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        manageTavelOfficBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageAirlinerBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageAirlinerBtn.setText("Manage Airliners");
        add(manageAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 151, -1, -1));

        jLabel1.setText("// -> ManageAirlinerJPanel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        searchBtn.setBackground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel2.setText("// -> ManageMasterFlightSchedualJPanel");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        manageTavelOfficBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageTavelOfficBtn.setText("Manage Travel Office");
        manageTavelOfficBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTavelOfficBtnActionPerformed(evt);
            }
        });
        add(manageTavelOfficBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setText("// .travelOfficeDirectory.travelOffice.getPendingTicket");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageTavelOfficBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTavelOfficBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageTavelOfficBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manageAirlinerBtn;
    private javax.swing.JButton manageTavelOfficBtn;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
