/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ButtonSide;

import Business.TravelAgency.TravelAgency;
import Business.TravelOffice.TravelOffice;
import Business.UserAccount.UserAccount;
import UserInterface.TravelOffice.BookingTicketJPanel;
import UserInterface.TravelOffice.ManageCustomerJPanel;
import UserInterface.TravelOffice.ManageTicketJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author gaomc
 */
public class TravelOfficeBtnJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelOfficeBtn
     */
    private TravelOffice travelOffice;
    private JPanel cardSequenceJPanel;
    private TravelAgency travelAgency;
    
    public TravelOfficeBtnJPanel(UserAccount userAccount, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency = travelAgency;
        this.travelOffice = (TravelOffice) userAccount.getMember();
        this.cardSequenceJPanel = cardSequenceJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        manageCustomerBtn = new javax.swing.JButton();
        bookTicketBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageCustomerBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageCustomerBtn.setText("Manage Customer");
        manageCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerBtnActionPerformed(evt);
            }
        });
        add(manageCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        bookTicketBtn.setBackground(new java.awt.Color(255, 255, 255));
        bookTicketBtn.setText("Book Ticket for a Customer");
        bookTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketBtnActionPerformed(evt);
            }
        });
        add(bookTicketBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 100));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Manage Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerBtnActionPerformed
        // TODO add your handling code here:
        ManageCustomerJPanel panel = new ManageCustomerJPanel(cardSequenceJPanel, travelOffice);
        cardSequenceJPanel.add(panel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_manageCustomerBtnActionPerformed

    private void bookTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketBtnActionPerformed
        // TODO add your handling code here:
        BookingTicketJPanel panel = new BookingTicketJPanel(cardSequenceJPanel, travelOffice);
        cardSequenceJPanel.add(panel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_bookTicketBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageTicketJPanel panel = new ManageTicketJPanel(travelOffice);
        cardSequenceJPanel.add(panel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookTicketBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton manageCustomerBtn;
    // End of variables declaration//GEN-END:variables
}
