/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import cargenerator.Car;
import javax.swing.JOptionPane;

import java.io.File;
import javax.swing.*;
import java.awt.Image;


/**
 *
 * @author gaomc
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(Car car) {
        initComponents();
        displayCar(car);
    }
    
    public void displayCar(Car car){
        String carBrand = car.getBrand();
        brandField.setText(carBrand);
        
        String carModel = car.getModel();
        modelField.setText(carModel);
        
        String carDriventrains = car.getDrivetrains();
        drivetrainsField.setText(carDriventrains);
        
        String carEngines = car.getEngines();
        enginesField.setText(carEngines);
        
        String carStyle = car.getStyle();
        styleField.setText(carStyle);
        
        String carExteriorColor = car.getExteriorColor();
        exteriorColorField.setText(carExteriorColor);
        
        String carInteriorColor = car.getInteriorColor();
        interiorColorField.setText(carInteriorColor);
        
        String carMSPR = car.getMspr();
        msprField.setText(carMSPR);
        
        String carFuelType = car.getFuelType();
        fuelTypeField.setText(carFuelType);
        
        String carMPG = car.getMpg();
        mpgField.setText(carMPG);
        
        String carMileage = car.getMileage();
        mileageField.setText(carMileage);
        
        String carTransmission = car.getTransmission();
        transmissionField.setText(carTransmission);
        
        String carSerialNum = car.getSerialNum();
        serialNumField.setText(carSerialNum);
        
        String carDimension = car.getDimension();
        dimensionField.setText(carDimension);
        
        String carCarFaxNum = car.getCarFaxNum();
        carFaxNumField.setText(carCarFaxNum);
        
        String photoPath = car.getImgPath();
        photoPathField.setText(photoPath);
        
        System.out.println(photoPath);
        
        photoComponent.setIcon(ResizeImage(photoPath));

    }

    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelField = new javax.swing.JTextField();
        fuelTypeLabel = new javax.swing.JLabel();
        drivetrainsField = new javax.swing.JTextField();
        mpgLabel = new javax.swing.JLabel();
        enginesField = new javax.swing.JTextField();
        mileageLabel = new javax.swing.JLabel();
        styleField = new javax.swing.JTextField();
        transmissionField = new javax.swing.JTextField();
        transmissionLabel = new javax.swing.JLabel();
        exteriorColorField = new javax.swing.JTextField();
        serialNumField = new javax.swing.JTextField();
        serialNumLabel = new javax.swing.JLabel();
        dimensionField = new javax.swing.JTextField();
        carFaxNumField = new javax.swing.JTextField();
        brandLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        drivetrainsLabel = new javax.swing.JLabel();
        enginesLabel = new javax.swing.JLabel();
        styleLabel = new javax.swing.JLabel();
        exteriorColorLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        brandField = new javax.swing.JTextField();
        interiorColorLabel = new javax.swing.JLabel();
        msprLabel = new javax.swing.JLabel();
        interiorColorField = new javax.swing.JTextField();
        dimensionLabel = new javax.swing.JLabel();
        msprField = new javax.swing.JTextField();
        carFaxLabel = new javax.swing.JLabel();
        fuelTypeField = new javax.swing.JTextField();
        mpgField = new javax.swing.JTextField();
        mileageField = new javax.swing.JTextField();
        photoComponent = new javax.swing.JLabel();
        photoPathField = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(modelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 264, 190, -1));

        fuelTypeLabel.setText("Fuel Type:");
        add(fuelTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 237, -1, -1));

        drivetrainsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivetrainsFieldActionPerformed(evt);
            }
        });
        add(drivetrainsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 296, 190, -1));

        mpgLabel.setText("MPG:");
        add(mpgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 267, -1, -1));

        enginesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginesFieldActionPerformed(evt);
            }
        });
        add(enginesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 328, 190, -1));

        mileageLabel.setText("Mileage:");
        add(mileageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 299, -1, -1));
        add(styleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 360, 190, -1));
        add(transmissionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 326, 139, -1));

        transmissionLabel.setText("Transmission:");
        add(transmissionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 331, -1, -1));
        add(exteriorColorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 392, 190, -1));
        add(serialNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 358, 139, -1));

        serialNumLabel.setText("Serial Number:");
        add(serialNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 363, -1, -1));

        dimensionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimensionFieldActionPerformed(evt);
            }
        });
        add(dimensionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 390, 139, -1));

        carFaxNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carFaxNumFieldActionPerformed(evt);
            }
        });
        add(carFaxNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 422, 139, -1));

        brandLabel.setText("Brand:");
        add(brandLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 237, -1, -1));

        modelLabel.setText("Model:");
        add(modelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 269, -1, -1));

        drivetrainsLabel.setText("Drivetrains:");
        add(drivetrainsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 301, -1, -1));

        enginesLabel.setText("Engines:");
        add(enginesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 333, -1, -1));

        styleLabel.setText("Style:");
        add(styleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 365, -1, -1));

        exteriorColorLabel.setText("ExteriorColor:");
        add(exteriorColorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 397, -1, -1));

        jLabel1.setFont(new java.awt.Font("Marion", 1, 24)); // NOI18N
        jLabel1.setText("View Your Own Car");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        brandField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandFieldActionPerformed(evt);
            }
        });
        add(brandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 232, 190, -1));

        interiorColorLabel.setText("InteriorColor:");
        add(interiorColorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 424, -1, 22));

        msprLabel.setText("MSPR");
        add(msprLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 458, -1, -1));

        interiorColorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interiorColorFieldActionPerformed(evt);
            }
        });
        add(interiorColorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 422, 190, -1));

        dimensionLabel.setText("Dimenssion:");
        add(dimensionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 395, -1, -1));
        add(msprField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 454, 190, -1));

        carFaxLabel.setText("CarFax Number:");
        add(carFaxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 427, -1, -1));
        add(fuelTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 232, 139, -1));
        add(mpgField, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 262, 139, -1));
        add(mileageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 294, 139, -1));
        add(photoComponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 64, 150, 150));
        add(photoPathField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 267, 30));

        jLabel3.setText("PhotoPath:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void drivetrainsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivetrainsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drivetrainsFieldActionPerformed

    private void enginesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enginesFieldActionPerformed

    private void dimensionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimensionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimensionFieldActionPerformed

    private void carFaxNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carFaxNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carFaxNumFieldActionPerformed

    private void brandFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandFieldActionPerformed

    private void interiorColorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interiorColorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interiorColorFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandField;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JLabel carFaxLabel;
    private javax.swing.JTextField carFaxNumField;
    private javax.swing.JTextField dimensionField;
    private javax.swing.JLabel dimensionLabel;
    private javax.swing.JTextField drivetrainsField;
    private javax.swing.JLabel drivetrainsLabel;
    private javax.swing.JTextField enginesField;
    private javax.swing.JLabel enginesLabel;
    private javax.swing.JTextField exteriorColorField;
    private javax.swing.JLabel exteriorColorLabel;
    private javax.swing.JTextField fuelTypeField;
    private javax.swing.JLabel fuelTypeLabel;
    private javax.swing.JTextField interiorColorField;
    private javax.swing.JLabel interiorColorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mileageField;
    private javax.swing.JLabel mileageLabel;
    private javax.swing.JTextField modelField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField mpgField;
    private javax.swing.JLabel mpgLabel;
    private javax.swing.JTextField msprField;
    private javax.swing.JLabel msprLabel;
    private javax.swing.JLabel photoComponent;
    private javax.swing.JLabel photoPathField;
    private javax.swing.JTextField serialNumField;
    private javax.swing.JLabel serialNumLabel;
    private javax.swing.JTextField styleField;
    private javax.swing.JLabel styleLabel;
    private javax.swing.JTextField transmissionField;
    private javax.swing.JLabel transmissionLabel;
    // End of variables declaration//GEN-END:variables
}
