/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PharmaceuticalManufacturer;

/**
 *
 * @author gaomc
 */
public class PharmManfAdminButtonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmManfAdminButtonJPanel
     */
    public PharmManfAdminButtonJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkRequestBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkRequestBtn.setBackground(new java.awt.Color(255, 255, 255));
        checkRequestBtn.setText("Check Request");
        add(checkRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkRequestBtn;
    // End of variables declaration//GEN-END:variables
}
