/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PharmaceuticalManufacturer.charity;

import business.enterprise.Enterprise;
import business.organization.pharmacy.CharityOrganization;
import business.useraccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author gaomc
 */
public class CharityWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form charityWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private CharityOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public CharityWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CharityOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
