/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.volunteer.doctor;

/**
 *
 * @author gaomc
 */
public class DoctorButtonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorButtonJPanel
     */
    public DoctorButtonJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        updateOwnInfoBtn = new javax.swing.JButton();
        requestMedicalBtn = new javax.swing.JButton();
        checkRecordBtn = new javax.swing.JButton();
        checkRemainQuestionBtn = new javax.swing.JButton();
        requestHospitalBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateOwnInfoBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateOwnInfoBtn.setText("Update Own Info");
        updateOwnInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOwnInfoBtnActionPerformed(evt);
            }
        });
        add(updateOwnInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        requestMedicalBtn.setBackground(new java.awt.Color(255, 255, 255));
        requestMedicalBtn.setText("Request Medical Care");
        requestMedicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestMedicalBtnActionPerformed(evt);
            }
        });
        add(requestMedicalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        checkRecordBtn.setBackground(new java.awt.Color(255, 255, 255));
        checkRecordBtn.setText("Check Records");
        checkRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRecordBtnActionPerformed(evt);
            }
        });
        add(checkRecordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        checkRemainQuestionBtn.setBackground(new java.awt.Color(255, 255, 255));
        checkRemainQuestionBtn.setText("Check Remain Questions");
        checkRemainQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRemainQuestionBtnActionPerformed(evt);
            }
        });
        add(checkRemainQuestionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        requestHospitalBtn.setBackground(new java.awt.Color(255, 255, 255));
        requestHospitalBtn.setText("Request Hospital Clinic");
        requestHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestHospitalBtnActionPerformed(evt);
            }
        });
        add(requestHospitalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateOwnInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOwnInfoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateOwnInfoBtnActionPerformed

    private void requestMedicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestMedicalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestMedicalBtnActionPerformed

    private void checkRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRecordBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkRecordBtnActionPerformed

    private void checkRemainQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRemainQuestionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkRemainQuestionBtnActionPerformed

    private void requestHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestHospitalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestHospitalBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkRecordBtn;
    private javax.swing.JButton checkRemainQuestionBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton requestHospitalBtn;
    private javax.swing.JButton requestMedicalBtn;
    private javax.swing.JButton updateOwnInfoBtn;
    // End of variables declaration//GEN-END:variables
}
