/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.volunteer;

/**
 *
 * @author gaomc
 */
public class VolunteerAdminButtonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerAdminButtonJPanel
     */
    public VolunteerAdminButtonJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qulificationInspectBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        qulificationInspectBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qulificationInspectBtn.setText("Check User Catalog");
        add(qulificationInspectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel1.setText("// check doctor qualification");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        qulificationInspectBtn1.setText("Qulification Inspection ");
        add(qulificationInspectBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 100, -1, -1));

        jLabel2.setText("// CRUD user (account) info");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton qulificationInspectBtn;
    private javax.swing.JButton qulificationInspectBtn1;
    // End of variables declaration//GEN-END:variables
}
