/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3sample.Interface;

import assignment3sample.Business.Car;
import assignment3sample.Business.CarList;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class AdminListCarJPanel extends javax.swing.JPanel {

    
    private List<Car> listCars;
    private CarList carList;
    private JPanel viewJPanel;

 

    AdminListCarJPanel(JPanel viewJPanel, List<Car> searchInfo, CarList carList) {
        initComponents();

        this.listCars = searchInfo;
        this.carList = carList;
        this.viewJPanel = viewJPanel;

        populate(listCars);    
    }
    
    public void populate(List<Car> listCars){
        DefaultTableModel dtm = (DefaultTableModel)carListTable.getModel();
        dtm.setRowCount(0);
        
        listCars.stream().map((car) -> {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = car;
            row[1] = car.getAvailble_city();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();
            row[4] = car.getManufactured_year();
            row[5] = car.getSerial_num();
            row[6] = car.isMaintenance_certificate();
            row[7] = car.isAvailable();
            row[8] = car.getModel_num();
            return row;
        }).forEachOrdered((row) -> {
            dtm.addRow(row);
        });
        
        if(listCars.size()==0){
            JOptionPane.showMessageDialog(null, "Cannot find a car like this!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManage = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        carListTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sndFilterBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManage.setText("Manage Car");
        add(lblManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        btnView.setBackground(new java.awt.Color(255, 255, 255));
        btnView.setText("View Product");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        carListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car INFO (Brand & Model)", "Available City", "Min_Seats", "Max_Seats", "Year", "Serial #", "Certificate", "Avaliability", "Model #"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(carListTable);
        if (carListTable.getColumnModel().getColumnCount() > 0) {
            carListTable.getColumnModel().getColumn(0).setPreferredWidth(0);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 128, 690, 113));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 690, 80));

        jLabel1.setText("View: Update & delete");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        sndFilterBtn.setBackground(new java.awt.Color(51, 102, 255));
        sndFilterBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        sndFilterBtn.setForeground(new java.awt.Color(255, 255, 255));
        sndFilterBtn.setText("Second Filter: Search agian by valid Certificate");
        sndFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sndFilterBtnActionPerformed(evt);
            }
        });
        add(sndFilterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
       int selectedRow = carListTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }else{
            Car car = (Car) carListTable.getValueAt(selectedRow, 0);
            AdminSigleCarJPanel panel = new AdminSigleCarJPanel(viewJPanel, car, carList);
            viewJPanel.add(panel);
            CardLayout layout = (CardLayout) viewJPanel.getLayout();
            layout.next(viewJPanel); 
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        viewJPanel.remove(this);
        CardLayout layout = (CardLayout) viewJPanel.getLayout();
        layout.previous(viewJPanel);
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void sndFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sndFilterBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<Car> sndSearchResult = (ArrayList) listCars.stream()
        .filter(car -> car.isMaintenance_certificate())
        .collect(Collectors.toList());

        populate(sndSearchResult);
    }//GEN-LAST:event_sndFilterBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnView;
    private javax.swing.JTable carListTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManage;
    private javax.swing.JButton sndFilterBtn;
    // End of variables declaration//GEN-END:variables
}
