/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3sample.Interface;

import assignment3sample.Business.Car;
import assignment3sample.Business.CarInformationList;
import assignment3sample.Business.CarList;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author tusiyu
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private CarList carList;
    
    
    public MainFrame() {
        initComponents();
        ArrayList<Car> carInfoList = CarInformationList.getCarList().carInfoList;
        carList = new CarList(carInfoList);
        for(Car c : carInfoList)
            System.out.println(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJSplitPane = new javax.swing.JSplitPane();
        rightJPanel = new javax.swing.JPanel();
        subJSplitPane2 = new javax.swing.JSplitPane();
        btnJPanel = new javax.swing.JPanel();
        viewJPanel = new javax.swing.JPanel();
        leftJPanel = new javax.swing.JPanel();
        adminBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        updateTimeTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainJSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainJSplitPane.setMinimumSize(new java.awt.Dimension(0, 0));
        mainJSplitPane.setPreferredSize(new java.awt.Dimension(1300, 900));

        rightJPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightJPanel.setLayout(new java.awt.CardLayout());

        subJSplitPane2.setDividerLocation(300);

        btnJPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnJPanel.setMinimumSize(new java.awt.Dimension(370, 0));
        btnJPanel.setPreferredSize(new java.awt.Dimension(370, 300));
        btnJPanel.setLayout(new java.awt.CardLayout());
        subJSplitPane2.setLeftComponent(btnJPanel);

        viewJPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewJPanel.setPreferredSize(new java.awt.Dimension(1000, 200));
        viewJPanel.setLayout(new java.awt.CardLayout());
        subJSplitPane2.setRightComponent(viewJPanel);

        rightJPanel.add(subJSplitPane2, "card2");

        mainJSplitPane.setRightComponent(rightJPanel);

        leftJPanel.setBackground(new java.awt.Color(51, 51, 51));
        leftJPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        leftJPanel.setPreferredSize(new java.awt.Dimension(1200, 80));
        leftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminBtn.setBackground(new java.awt.Color(255, 255, 255));
        adminBtn.setText("Admin");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(adminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        userBtn.setBackground(new java.awt.Color(255, 255, 255));
        userBtn.setText("User");
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 85, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        leftJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        updateTimeTxt.setBackground(new java.awt.Color(51, 51, 51));
        updateTimeTxt.setForeground(new java.awt.Color(255, 255, 255));
        updateTimeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTimeTxtActionPerformed(evt);
            }
        });
        leftJPanel.add(updateTimeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 270, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Last Update Time");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        leftJPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        mainJSplitPane.setLeftComponent(leftJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainJSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainJSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        // TODO add your handling code here:
        UserBtnJPanel userBtnJpanel = new UserBtnJPanel(carList,viewJPanel);
        btnJPanel.add("UserBtnJPanel",userBtnJpanel);
        CardLayout leftlayout = (CardLayout) btnJPanel.getLayout();
        leftlayout.next(btnJPanel);
        
        UserMainJPanel userMainJPanel = new UserMainJPanel();
        viewJPanel.add("userViewJPanel",userMainJPanel);
        CardLayout rightlayout = (CardLayout) viewJPanel.getLayout();
        rightlayout.next(viewJPanel);
    }//GEN-LAST:event_userBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
        AdminBtnJPanel adminBtnJpanel = new AdminBtnJPanel(carList,viewJPanel);
        btnJPanel.add("AdminBtnJPanel",adminBtnJpanel);
        CardLayout leftlayout = (CardLayout) btnJPanel.getLayout();
        leftlayout.next(btnJPanel);
        
        AdminMainJPanel adminMainJPanel = new AdminMainJPanel();
        viewJPanel.add("AdminViewJPanel",adminMainJPanel);
        CardLayout rightlayout = (CardLayout) viewJPanel.getLayout();
        rightlayout.next(viewJPanel);

    }//GEN-LAST:event_adminBtnActionPerformed

    private void updateTimeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTimeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTimeTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateTimeTxt.setText(carList.getTime().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JPanel btnJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JSplitPane mainJSplitPane;
    private javax.swing.JPanel rightJPanel;
    private javax.swing.JSplitPane subJSplitPane2;
    private javax.swing.JTextField updateTimeTxt;
    private javax.swing.JButton userBtn;
    private javax.swing.JPanel viewJPanel;
    // End of variables declaration//GEN-END:variables

}
