/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3sample.Interface;

import assignment3sample.Business.Car;
import assignment3sample.Business.CarList;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gaomc
 */
public class UserListCarJPanel extends javax.swing.JPanel {


    private JPanel viewJPanel;
    private CarList carList;
    ArrayList<Car> searchResult;
    
    UserListCarJPanel(JPanel viewJPanel, ArrayList<Car> searchResult, CarList carList) {
        
        initComponents();
        this.viewJPanel = viewJPanel;
        this.searchResult = searchResult;
        this.carList = carList;
        populate(searchResult);
    }
    private void populate(List<Car> searchResult){
        
        DefaultTableModel dtm = (DefaultTableModel)carListTable.getModel();
        dtm.setRowCount(0);
        
        searchResult.stream().map((car) -> {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = car;
            row[1] = car.getAvailble_city();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();
            row[4] = car.getManufactured_year();
            row[5] = car.getSerial_num();
            row[6] = car.isMaintenance_certificate();
            row[7] = car.isAvailable();
            row[8] = car.getModel_num();
            return row;
        }).forEachOrdered((row) -> {
            dtm.addRow(row);
        });
        
        if(searchResult.size()==0){
            JOptionPane.showMessageDialog(null, "Cannot find a car like this!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManage = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        sndFilterBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        carListTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManage.setText("View Cars");
        add(lblManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 94, -1, -1));

        backBtn1.setBackground(new java.awt.Color(255, 255, 255));
        backBtn1.setText("<< Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        add(backBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 680, 80));

        sndFilterBtn.setBackground(new java.awt.Color(51, 102, 255));
        sndFilterBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        sndFilterBtn.setForeground(new java.awt.Color(255, 255, 255));
        sndFilterBtn.setText("Second Filter: Search agian by valid Certificate");
        sndFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sndFilterBtnActionPerformed(evt);
            }
        });
        add(sndFilterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        carListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car INFO (Brand & Model)", "Available City", "Min_Seats", "Max_Seats", "Year", "Serial #", "Certificate", "Avaliability", "Model #"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(carListTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 128, 740, 113));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("^");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        viewBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("^");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sndFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sndFilterBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<Car> sndSearchResult = (ArrayList) searchResult.stream()
                .filter(car -> car.isMaintenance_certificate())
                .collect(Collectors.toList());
        
        populate(sndSearchResult);
    }//GEN-LAST:event_sndFilterBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        viewJPanel.remove(this);
        CardLayout layout = (CardLayout) viewJPanel.getLayout();
        layout.previous(viewJPanel);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = carListTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a Row!");
            return;
        }else{
            Car car = (Car) carListTable.getValueAt(selectedRow, 0);
            UserViewSingleCarJPanel userViewSingleCarJPanel = new UserViewSingleCarJPanel(viewJPanel, car);
            viewJPanel.add(userViewSingleCarJPanel);
            CardLayout layout = (CardLayout) viewJPanel.getLayout();
            layout.next(viewJPanel);
        }
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn1;
    private javax.swing.JTable carListTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblManage;
    private javax.swing.JButton sndFilterBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
