/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3sample.Interface;

/**
 *
 * @author gaomc
 */
public class UserMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserMainJPanel
     */
    public UserMainJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 12)); // NOI18N
        jLabel2.setText("Click buttons in left, the results will shows here.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 270, 50));

        jLabel3.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 24)); // NOI18N
        jLabel3.setText("User Functions");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 190, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
