/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.volunteer.hospitalContact;

/**
 *
 * @author gaomc
 */
public class HospitalContactButtonJPanel extends javax.swing.JPanel {

    /** Creates new form HospitalContactButtonJPanel */
    public HospitalContactButtonJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processHospitalRequestBtn = new javax.swing.JButton();
        checkHospitalAvalBtn1 = new javax.swing.JButton();
        processHospitalRequestBtn1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processHospitalRequestBtn.setText("Check Hospital Reply");
        add(processHospitalRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        checkHospitalAvalBtn1.setText("Check Hospital Avaliability");
        add(checkHospitalAvalBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        processHospitalRequestBtn1.setText("Process Patients Request");
        add(processHospitalRequestBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkHospitalAvalBtn1;
    private javax.swing.JButton processHospitalRequestBtn;
    private javax.swing.JButton processHospitalRequestBtn1;
    // End of variables declaration//GEN-END:variables

}
